# Generated by Django 3.0.5 on 2020-04-22 08:54

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('pull_id', models.IntegerField(blank=True, null=True)),
                ('html_url', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pusher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_username', models.CharField(blank=True, max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GitEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=250)),
                ('before', models.CharField(blank=True, max_length=250)),
                ('after', models.CharField(blank=True, max_length=250)),
                ('base_ref', models.CharField(blank=True, max_length=250, null=True)),
                ('compare', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_pull_request', models.BooleanField(default=False)),
                ('is_push', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitevents_pull_request', to='GitHub.PullRequest')),
                ('pusher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitevents_pusher', to='GitHub.Pusher')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitevents_repository', to='GitHub.GitRepo')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitevents_sender', to='GitHub.Sender')),
            ],
        ),
    ]
